import type { Metadata } from "next";
import { Ubuntu, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
});

// FIXED: Added explicit weights
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-opensans", // Note: You removed the dash, so we match this
});

export const metadata: Metadata = {
  title: "Akti Boat Rentals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Match variables exactly
        className={`${ubuntu.variable} ${openSans.variable} font-open antialiased`}
      >
        <Navbar />
        <main className="w-full mx-auto">{children}</main>
        <WhatsAppButton />
        <Footer />
      </body>
    </html>
  );
}
