import type { Metadata } from "next";
import { Ubuntu, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

// 1. Configure Ubuntu (Static Font: Needs specific weights)
const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-ubuntu",
});

// 2. Configure Open Sans (Variable Font: Automatically supports 300-800)
const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // 3. Add both font variables to the body so Tailwind can see them
        className={`${ubuntu.variable} ${openSans.variable} antialiased bg-white text-[#0D4168]`}
      >
        <Navbar />

        {/* 4. Main Wrapper: Width restricted, centered, NO padding */}
        <main className="w-full mx-auto">{children}</main>
      </body>
    </html>
  );
}
